name: client
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  device_preview: ^1.2.0
  openapi:
    path: ./api_clients
  riverpod_annotation: ^2.3.5
  speech_to_text: ^7.0.0
  avatar_glow: ^3.0.1
  logger: ^2.4.0
  http: ^1.2.2
  loading_animation_widget: ^1.2.1
  animated_text_kit: ^4.2.2
  flutter_tts: ^4.0.2
  sign_in_button: ^3.2.0
  flutter_html: ^3.0.0-beta.2
  camera: ^0.11.0+2
  file_saver: ^0.2.14
  awesome_dialog: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0
flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/cautions.html
flutter_intl:
  enabled: true
