version: "3"

services:
  nginx:
    image: nginx:1.27.2-alpine
    container_name: school-interview-nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certificaate/server.crt:/etc/nginx/conf.d/server.crt
      - ./certificate/private.key:/etc/nginx/conf.d/private.key
    profiles:
      - nginx
    depends_on:
      - backend-app
  backend-app:
    build: .
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - ./launch-server-docker.sh:/app/launch-server-docker.sh
      - ./alembic.ini:/app/alembic.ini
      - ./migrations:/app/migrations
      - ./.env:/app/.env
      - ./.env.local:/app/.env.local
      - ./pdf:/app/pdf
    ports:
      - 8000:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PYTHONPATH: "$PYTHONPATH:/app/src"
      DATABASE_URL: "postgresql://user:postgres@db:5432/school-interview"
    depends_on:
      - db
    profiles:
      - backend
  db:
    image: postgres:14
    container_name: school-interivew-postgres
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "postgres"
    profiles:
      - db
  testing:
    build:
      context: .
      dockerfile: ./test/Dockerfile
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - ./launch-server-docker.sh:/app/launch-server-docker.sh
      - ./alembic.ini:/app/alembic.ini
      - ./migrations:/app/migrations
      - ./.env:/app/.env
      - ./.env.local:/app/.env.local
      - ./pdf:/app/pdf
    environment:
      PYTHONPATH: "$PYTHONPATH:/app/src"
    profiles:
      - testing

volumes:
  db-store:
