services:
  backend-app:
    build: .
    volumes:
      - ./web:/app/web
      - ./src:/app/src
      - ./test:/app/test
      - ./launch-server-docker.sh:/app/launch-server-docker.sh
      - ./alembic.ini:/app/alembic.ini
      - ./migrations:/app/migrations
      - ./.env:/app/.env
      - ./.env.local:/app/.env.local
      - ./pdf:/app/pdf
    ports:
      - 8000:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PYTHONPATH: "$PYTHONPATH:/app/src"
      DATABASE_URL: "postgresql://user:postgres@db:5432/school-interview"
    depends_on:
      - db
    profiles:
      - backend
  debug:
    build: .
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - ./launch-server-docker.sh:/app/launch-server-docker.sh
      - ./alembic.ini:/app/alembic.ini
      - ./migrations:/app/migrations
      - ./.env:/app/.env
      - ./.env.local:/app/.env.local
      - ./pdf:/app/pdf
    ports:
      - 8000:8000
      - 5678:5678
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PYTHONPATH: "$PYTHONPATH:/app/src"
      DATABASE_URL: "postgresql://user:postgres@db:5432/school-interview"
      DEBUG: "True"
    depends_on:
      - db
    profiles:
      - debug
  db:
    image: postgres:14
    container_name: school-interivew-postgres
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "postgres"
    profiles:
      - db
  testing:
    build:
      context: .
      dockerfile: ./test/Dockerfile
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - ./launch-server-docker.sh:/app/launch-server-docker.sh
      - ./alembic.ini:/app/alembic.ini
      - ./migrations:/app/migrations
      - ./.env:/app/.env
      - ./.env.local:/app/.env.local
      - ./pdf:/app/pdf
    environment:
      PYTHONPATH: "$PYTHONPATH:/app/src"
    profiles:
      - testing

volumes:
  db-store:
