version: "3"

services:
  backend-app:
    build: .
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - ./launch-server.sh:/app/launch-server.sh
      - ./alembic.ini:/app/alembic.ini
      - ./migrations:/app/migrations
      - ./.env:/app/.env
    ports:
      - 8000:8000
    environment:
      PYTHONPATH: "$PYTHONPATH:/app/src"
      DATABASE_URL: "postgresql://user:postgres@db:5432/school-interview"
    depends_on:
      - db
  db:
    image: postgres:14
    container_name: school-interivew-postgres
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "postgres"
volumes:
  db-store:
