name: タスク
description: タスクを作成する
body:
  - type: dropdown
    id: related
    attributes:
      label: 関連するもの
      description: このタスクが関連するものを選択してください。
      multiple: false
      options:
        - "Backend"
        - "Client"
        - "Other"
        - "All"
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: タスクの種類
      description: このタスクの種類を選択してください。
      multiple: false
      options:
        - "Feature"
        - "Bug"
        - "Improvement"
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: 概要
      description: このタスクの目的や背景について簡潔に記述してください。
    validations:
      required: false