"""grade → semesterに変更

Revision ID: 1d7536de2605
Revises: dc1d3dd0d750
Create Date: 2024-09-22 01:48:24.437464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d7536de2605'
down_revision: Union[str, None] = 'dc1d3dd0d750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('semester', sa.Integer(), nullable=False))
    op.drop_column('Users', 'grade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('Users', 'semester')
    # ### end Alembic commands ###
