"""create tables

Revision ID: 211865b687a2
Revises: 
Create Date: 2024-10-09 00:39:34.240997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '211865b687a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('InterviewQuestions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order')
    )
    op.create_table('Teachers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('InterviewSessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['progress'], ['InterviewQuestions.order'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['Teachers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('WebsocketConnections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('socket_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('InterviewAnalytics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('fail_to_move_to_next_grade', sa.Boolean(), nullable=False),
    sa.Column('deviation_from_preferred_credit_level', sa.Float(), nullable=False),
    sa.Column('deviation_from_minimum_attendance_rate', sa.Float(), nullable=False),
    sa.Column('high_attendance_low_gpa_rate', sa.Float(), nullable=False),
    sa.Column('low_atendance_and_low_gpa_rate', sa.Float(), nullable=False),
    sa.Column('support_necessity_level', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['InterviewSessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('InterviewRecords',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('total_earned_credits', sa.Integer(), nullable=True),
    sa.Column('planned_credits', sa.Integer(), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('attendance_rate', sa.Float(), nullable=True),
    sa.Column('concern', sa.String(), nullable=True),
    sa.Column('prefer_in_person_interview', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['InterviewSessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('InterviewRecords')
    op.drop_table('InterviewAnalytics')
    op.drop_table('WebsocketConnections')
    op.drop_table('InterviewSessions')
    op.drop_table('Users')
    op.drop_table('Teachers')
    op.drop_table('InterviewQuestions')
    # ### end Alembic commands ###
