"""create tables

Revision ID: 2bae78884435
Revises: f98708bce6da
Create Date: 2024-08-30 14:45:06.414196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bae78884435'
down_revision: Union[str, None] = 'f98708bce6da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('InterviewQuestions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('question', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order')
    )
    op.create_table('Teachers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('student_id', sa.String(length=7), nullable=False),
    sa.Column('department', sa.String(length=30), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('AuthTokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Connections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('socket_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('InterviewSessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('teacher_id', sa.String(), nullable=False),
    sa.Column('start_at', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['progress'], ['InterviewQuestions.order'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['Teachers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('InterviewRecords',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('total_earned_credits', sa.Integer(), nullable=True),
    sa.Column('planned_credits', sa.Integer(), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('attendance_rate', sa.Float(), nullable=True),
    sa.Column('concern', sa.String(), nullable=True),
    sa.Column('prefer_in_person_interview', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['InterviewSessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('InterviewRecords')
    op.drop_table('InterviewSessions')
    op.drop_table('Connections')
    op.drop_table('AuthTokens')
    op.drop_table('Users')
    op.drop_table('Teachers')
    op.drop_table('InterviewQuestions')
    # ### end Alembic commands ###
