"""Teachersにimage_urlフィールドを追加

Revision ID: 6871aef4c6ce
Revises: e134f97cf0c7
Create Date: 2024-11-29 00:48:31.700701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6871aef4c6ce'
down_revision: Union[str, None] = 'e134f97cf0c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Teachers', sa.Column('image_url', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Teachers', 'image_url')
    # ### end Alembic commands ###
