"""InterviewSessionとInterviewQuestionのリレーション

Revision ID: 6dcb9bda78ba
Revises: b3aa903710c4
Create Date: 2024-11-21 22:23:42.251242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dcb9bda78ba'
down_revision: Union[str, None] = 'b3aa903710c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('InterviewSessions', sa.Column('current_question_id', sa.Uuid(), nullable=False))
    op.drop_constraint('InterviewSessions_progress_fkey', 'InterviewSessions', type_='foreignkey')
    op.create_foreign_key(None, 'InterviewSessions', 'InterviewQuestions', ['current_question_id'], ['id'])
    op.drop_column('InterviewSessions', 'progress')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('InterviewSessions', sa.Column('progress', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'InterviewSessions', type_='foreignkey')
    op.create_foreign_key('InterviewSessions_progress_fkey', 'InterviewSessions', 'InterviewQuestions', ['progress'], ['order'])
    op.drop_column('InterviewSessions', 'current_question_id')
    # ### end Alembic commands ###
