"""interview_analyticsにstart_atとend_atフィールドを追加

Revision ID: 78857c0fbaeb
Revises: e134f97cf0c7
Create Date: 2024-11-28 21:33:27.253488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78857c0fbaeb'
down_revision: Union[str, None] = 'e134f97cf0c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('InterviewAnalytics', sa.Column('start_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('InterviewAnalytics', sa.Column('end_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('InterviewAnalytics', 'end_at')
    op.drop_column('InterviewAnalytics', 'start_at')
    # ### end Alembic commands ###
