"""InterviewQuestionModelにgroupを追加

Revision ID: 9164bc7d20d8
Revises: af7ddd3f00c5
Create Date: 2024-11-28 03:31:05.238023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9164bc7d20d8'
down_revision: Union[str, None] = 'af7ddd3f00c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'InterviewRecords', 'InterviewQuestions', ['question_id'], ['id'])
    op.create_foreign_key(None, 'InterviewSessions', 'InterviewQuestions', ['current_question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'InterviewSessions', type_='foreignkey')
    op.drop_constraint(None, 'InterviewRecords', type_='foreignkey')
    # ### end Alembic commands ###
