"""AdminのuserIdのリレーション忘れてたので修正

Revision ID: 94f9485a9cc2
Revises: 5e8093960c72
Create Date: 2024-10-09 00:46:12.065073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94f9485a9cc2'
down_revision: Union[str, None] = '5e8093960c72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Admins', 'Users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Admins', type_='foreignkey')
    # ### end Alembic commands ###
