"""Userの削除に合わせて他のテーブルの行も削除されるようにしました（CASCADEE処理）

Revision ID: 98d8f4765cd0
Revises: b57c76fac34d
Create Date: 2024-11-10 13:54:22.816521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98d8f4765cd0'
down_revision: Union[str, None] = 'b57c76fac34d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Admins_user_id_fkey', 'Admins', type_='foreignkey')
    op.create_foreign_key(None, 'Admins', 'Users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('InterviewAnalytics_session_id_fkey', 'InterviewAnalytics', type_='foreignkey')
    op.create_foreign_key(None, 'InterviewAnalytics', 'InterviewSessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('InterviewRecords_session_id_fkey', 'InterviewRecords', type_='foreignkey')
    op.create_foreign_key(None, 'InterviewRecords', 'InterviewSessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('InterviewSessions_user_id_fkey', 'InterviewSessions', type_='foreignkey')
    op.create_foreign_key(None, 'InterviewSessions', 'Users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('Students_user_id_fkey', 'Students', type_='foreignkey')
    op.create_foreign_key(None, 'Students', 'Users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Students', type_='foreignkey')
    op.create_foreign_key('Students_user_id_fkey', 'Students', 'Users', ['user_id'], ['id'])
    op.drop_constraint(None, 'InterviewSessions', type_='foreignkey')
    op.create_foreign_key('InterviewSessions_user_id_fkey', 'InterviewSessions', 'Users', ['user_id'], ['id'])
    op.drop_constraint(None, 'InterviewRecords', type_='foreignkey')
    op.create_foreign_key('InterviewRecords_session_id_fkey', 'InterviewRecords', 'InterviewSessions', ['session_id'], ['id'])
    op.drop_constraint(None, 'InterviewAnalytics', type_='foreignkey')
    op.create_foreign_key('InterviewAnalytics_session_id_fkey', 'InterviewAnalytics', 'InterviewSessions', ['session_id'], ['id'])
    op.drop_constraint(None, 'Admins', type_='foreignkey')
    op.create_foreign_key('Admins_user_id_fkey', 'Admins', 'Users', ['user_id'], ['id'])
    # ### end Alembic commands ###
