"""InterviewAnalyticsにプロパティを追加

Revision ID: a165a7b9668d
Revises: 2516caaaf219
Create Date: 2024-09-21 18:59:03.338955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a165a7b9668d'
down_revision: Union[str, None] = '2516caaaf219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('InterviewAnalytics', sa.Column('fail_to_move_to_next_grade', sa.Boolean(), nullable=False))
    op.add_column('InterviewAnalytics', sa.Column('deviation_from_preferred_credit_level', sa.Float(), nullable=False))
    op.add_column('InterviewAnalytics', sa.Column('deviation_from_minimum_attendance_rate', sa.Float(), nullable=False))
    op.add_column('InterviewAnalytics', sa.Column('high_attendance_low_gpa_rate', sa.Float(), nullable=False))
    op.add_column('InterviewAnalytics', sa.Column('low_atendance_and_low_gpa_rate', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('InterviewAnalytics', 'low_atendance_and_low_gpa_rate')
    op.drop_column('InterviewAnalytics', 'high_attendance_low_gpa_rate')
    op.drop_column('InterviewAnalytics', 'deviation_from_minimum_attendance_rate')
    op.drop_column('InterviewAnalytics', 'deviation_from_preferred_credit_level')
    op.drop_column('InterviewAnalytics', 'fail_to_move_to_next_grade')
    # ### end Alembic commands ###
