"""InterviewSessionのstart_atをintからdatetimeへ変更

Revision ID: a2295f7fb79b
Revises: 63179968c91e
Create Date: 2024-09-01 16:52:54.758264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2295f7fb79b'
down_revision: Union[str, None] = '63179968c91e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('InterviewSessions', 'start_at',
                    existing_type=sa.INTEGER(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=False,
                    postgresql_using='to_timestamp(start_at)::timestamp with time zone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('InterviewSessions', 'start_at',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.INTEGER(),
                    existing_nullable=False)
    # ### end Alembic commands ###
