"""InterviewGroupとInterviewQuestionの半構造形式対応

Revision ID: ad28d76f3574
Revises: 98d8f4765cd0
Create Date: 2024-11-20 23:34:48.012934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad28d76f3574'
down_revision: Union[str, None] = '98d8f4765cd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('InterviewQuestions', sa.Column('group_id', sa.Uuid(), nullable=False))
    op.add_column('InterviewQuestions', sa.Column('condition_target_operand_data_type', sa.String(length=5), nullable=True))
    op.add_column('InterviewQuestions', sa.Column('condition_left_operand', sa.String(length=10), nullable=True))
    op.add_column('InterviewQuestions', sa.Column('condition_left_operator', sa.String(length=2), nullable=True))
    op.add_column('InterviewQuestions', sa.Column('condition_right_operand', sa.String(length=10), nullable=True))
    op.add_column('InterviewQuestions', sa.Column('condition_right_operator', sa.String(length=2), nullable=True))
    op.add_column('InterviewQuestions', sa.Column('extraction_data_type', sa.String(length=5), nullable=False))
    op.create_foreign_key(None, 'InterviewQuestions', 'InterviewQuestionGroups', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'InterviewQuestions', type_='foreignkey')
    op.drop_column('InterviewQuestions', 'extraction_data_type')
    op.drop_column('InterviewQuestions', 'condition_right_operator')
    op.drop_column('InterviewQuestions', 'condition_right_operand')
    op.drop_column('InterviewQuestions', 'condition_left_operator')
    op.drop_column('InterviewQuestions', 'condition_left_operand')
    op.drop_column('InterviewQuestions', 'condition_target_operand_data_type')
    op.drop_column('InterviewQuestions', 'group_id')
    # ### end Alembic commands ###
