"""InterviewQuestionModel.orderのunique制約を外しました

Revision ID: af7ddd3f00c5
Revises: 7acd500ea25f
Create Date: 2024-11-28 02:33:57.819363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af7ddd3f00c5'
down_revision: Union[str, None] = '7acd500ea25f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('InterviewQuestions_order_key', 'InterviewQuestions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('InterviewQuestions_order_key', 'InterviewQuestions', ['order'])
    # ### end Alembic commands ###
