"""InterviewRecordのモデルをアップデート

Revision ID: b3aa903710c4
Revises: ad28d76f3574
Create Date: 2024-11-21 00:07:07.808181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3aa903710c4'
down_revision: Union[str, None] = 'ad28d76f3574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('InterviewRecords', sa.Column('question_id', sa.Uuid(), nullable=False))
    op.add_column('InterviewRecords', sa.Column('extracted_data', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'InterviewRecords', 'InterviewQuestions', ['question_id'], ['id'])
    op.drop_column('InterviewRecords', 'concern')
    op.drop_column('InterviewRecords', 'total_earned_credits')
    op.drop_column('InterviewRecords', 'gpa')
    op.drop_column('InterviewRecords', 'attendance_rate')
    op.drop_column('InterviewRecords', 'prefer_in_person_interview')
    op.drop_column('InterviewRecords', 'planned_credits')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('InterviewRecords', sa.Column('planned_credits', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('InterviewRecords', sa.Column('prefer_in_person_interview', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('InterviewRecords', sa.Column('attendance_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('InterviewRecords', sa.Column('gpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('InterviewRecords', sa.Column('total_earned_credits', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('InterviewRecords', sa.Column('concern', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'InterviewRecords', type_='foreignkey')
    op.drop_column('InterviewRecords', 'extracted_data')
    op.drop_column('InterviewRecords', 'question_id')
    # ### end Alembic commands ###
