"""set nullable to some properties in Student

Revision ID: b57c76fac34d
Revises: 94f9485a9cc2
Create Date: 2024-10-20 11:02:35.447711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b57c76fac34d'
down_revision: Union[str, None] = '94f9485a9cc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Students', 'student_id',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)
    op.alter_column('Students', 'department',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('Students', 'semester',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Students', 'semester',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Students', 'department',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('Students', 'student_id',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)
    # ### end Alembic commands ###
