"""ConnectionからWebsocketConnectionへ変更

Revision ID: d356317ce177
Revises: a2295f7fb79b
Create Date: 2024-09-01 19:55:16.673262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd356317ce177'
down_revision: Union[str, None] = 'a2295f7fb79b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('WebsocketConnections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('socket_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Connections')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Connections',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('socket_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], name='Connections_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Connections_pkey')
    )
    op.drop_table('WebsocketConnections')
    # ### end Alembic commands ###
