"""grade → semesterに変更

Revision ID: dc1d3dd0d750
Revises: a165a7b9668d
Create Date: 2024-09-22 01:47:48.355987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc1d3dd0d750'
down_revision: Union[str, None] = 'a165a7b9668d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
