"""adviseカラムの追加（InterviewAnalytics）

Revision ID: e134f97cf0c7
Revises: 98d8f4765cd0
Create Date: 2024-11-19 17:58:38.572662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e134f97cf0c7'
down_revision: Union[str, None] = '98d8f4765cd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Advises')
    op.add_column('InterviewAnalytics', sa.Column('advise', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('InterviewAnalytics', 'advise')
    op.create_table('Advises',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('interview_analytics_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('advise', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['interview_analytics_id'], ['InterviewAnalytics.id'], name='Advises_interview_analytics_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Advises_pkey')
    )
    # ### end Alembic commands ###
