"""InterviewQuestionにpromptプロパティを追加

Revision ID: efb2eff20cce
Revises: d356317ce177
Create Date: 2024-09-16 18:58:03.357559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efb2eff20cce'
down_revision: Union[str, None] = 'd356317ce177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('InterviewQuestions', sa.Column('prompt', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('InterviewQuestions', 'prompt')
    # ### end Alembic commands ###
