name: Client CI

on:
  pull_request:
    paths:
      - "client/**"
    types: [ opened, edited, reopened, synchronize ]

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"

      - name: Flutter Clean and Pub Get
        run: |
          cd client
          flutter clean
          flutter pub get

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Analyze Code
        run: |
          cd client
          flutter analyze --no-fatal-infos --no-fatal-warnings

  #  test:
  #    name: Test
  #    runs-on: ubuntu-latest
  #    needs: prepare
  #    steps:
  #      - name: Checkout repository
  #        uses: actions/checkout@v3
  #
  #      - name: Set up Flutter
  #        uses: subosito/flutter-action@v2
  #        with:
  #          flutter-version: stable
  #
  #      - name: Run Tests
  #        run: |
  #          cd client
  #          flutter test --coverage

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Build Web App
        run: |
          cd client
          flutter build web