name: UnitTest
on: push

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: setup python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3
        with:
          python-version: 3.12
      - name: cd backend
        run: cd backend
      - name: install dependencies
        run: poetry install --no-root
      - name: run tests
        run: poetry run pytest
