name: UnitTest
on: push

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: cd backend
        run: cd backend
      - name: setup python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3
        with:
          python-version: 3.12
      - name: restore cache
        uses: actions/cache/restore@v3
        with:
          path: backend/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('backend/pyproject.toml') }}
      - name: install poetry
        uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a
      - name: install dependencies
        run: poetry install --no-root
        working-directory: backend
      - name: Cache venv dependencies
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          path: backend/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('backend/pyproject.toml') }}
      - name: run tests
        run: poetry run pytest
        working-directory: backend
